---
- name: Create onelink SSL cert
  hosts: ansible
  gather_facts: False
  vars:
 #   trust: "yes"
  vars_prompt:
       - name: "server_name"
         prompt: type server name
         private: no

       - name: "server_ip"
         prompt: type server IP
         private: no

       - name: "passphrase"
         prompt: type pass phrase
         private: yes

#       - name: "trust"
#         prompt: Yes or No
#         default: Yes
#         private: no
  tasks:
    - name: Prompt for server name and password
      ansible.builtin.template:
        src: "/root/semaphore/playbooks/templates/create-server-cert.sh"
        dest: /root/autocert
        mode: '0755'
        remote_src: yes

    - name: Delete files in output directory before continuing
      ansible.builtin.find:
        paths: /root/autocert/output
        file_type: file
      register: files_to_remove

    - name: Delete files
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ files_to_remove.files }}"

    - name: run create-server-cert.sh
      ansible.builtin.expect:
        command: /root/autocert/create-server-cert.sh
        chdir: /root/autocert/
        responses:
          "Enter pass phrase for /root/autocert/ca/key/paltronics-ca-1.key:": "{{ passphrase }}"
#          "Trust this certificate? [no]:  ": "{{ trust }}"
      become: yes
      register: shell_result
      
    - name: move over certs to URL
      ansible.builtin.copy:
        src: '/root/autocert/output/{{ server_name }}.ks'
        dest: '/var/www/html/certs/'
        remote_src: yes
      become: yes
