
---
#
- hosts: uslv
  connection: local
  gather_facts: True
  remote_user: root
  vars:
    notes: Created by Ansible
  #vars_files: vsphere_uslv_vars.yml
  vars_prompt:
#       - name: vcenter_username
#         prompt: type vcenter username
       - name: vcenter_password
         prompt: type vcenter password
         private: yes

  tasks:
#- name: Check for required variables
#  fail: msg="Must pass name and group to -e"
#  when: name is not defined or group is not defined

#- name: Check for vSphere access parameters
#  fail: msg="Must set vcenter_user and vcenter_pass in a Vault"
#  when: (vcenter_user is not defined) or (vcenter_pass is not defined)

  - name: Add owner to VM's
    vmware_guest_custom_attributes:
      validate_certs: False
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      name: "{{ item }}"
      attributes:
        - name: Owner
          value: "{{ vcenter_username }}"
    with_items:
       - "{{ groups['uslv15'] }}"
    delegate_to: localhost
